[package]
name = "udp_listener"
version = "1.0.0"
authors = ["Drake Tetreault <ekardnt@ekardnt.com>"]
edition = "2018"
description = "A simple program to dump incoming UDP traffic to the terminal."
license = "CC0-1.0"